apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: swim

resources:
  - ../../base

images:
  - name: swim-tfdm-consumer
    newName: ghcr.io/f03809/swim-tfdm-consumer
    newTag: latest
