apiVersion: apps/v1
kind: Deployment
metadata:
  name: swim-tfdm-consumer
  namespace: swim
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swim-tfdm-consumer
  template:
    metadata:
      labels:
        app: swim-tfdm-consumer
        component: api
    spec:
      containers:
      - name: consumer
        image: swim-tfdm-consumer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: RUN_MODE
          value: "api"
        - name: MONGODB_URL
          value: "mongodb://10.0.0.16:27017,10.1.1.27:27017/?replicaSet=rs0"
        - name: MONGODB_DB
          value: "swim_tfdm_consumer"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "10.0.0.94:9092"
        - name: KAFKA_TOPIC
          value: "faa-tfdm-raw"
        - name: KAFKA_GROUP_ID
          value: "swim-tfdm-consumer"
        - name: JWT_SECRET
          value: "change-me-please-replace-this-in-production-with-a-secure-secret"
        - name: ADMIN_SESSION_SECRET
          value: "change-me-admin-session-please-replace-in-production"
